<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KyWigRemote.Core\KyWigRemote.Core.csproj" />
    <ProjectReference Include="..\KyWigRemote.Shared.UI\KyWigRemote.Shared.UI.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\assets\brand\admin.ico</ApplicationIcon>
  </PropertyGroup>

</Project>